---
# Variables here are applicable to hybrid host groups.

rhdm_central_controller_usr: controllerUsr
rhdm_central_controller_pwd: controllerPwd

# Enable MANAGED mode for the KIE Server.
org_kie_server_controller_user: "{{ rhdm_central_controller_usr }}"
org_kie_server_controller_pwd: "{{ rhdm_central_controller_pwd }}"
