---
- name: create {{ rhdm_central_data }} directory
  file:
    path: "{{ rhdm_central_data }}"
    state: directory

- name: create {{ kie_maven_settings_custom }}
  template:
    src: settings.xml.j2
    dest: "{{ kie_maven_settings_custom }}"

- name: create setup.cli
  template:
    src: setup.cli.j2
    dest: "{{ rhdm_central_temp }}/setup.cli"

- name: run setup.cli JBoss configuration
  command: "{{ rhdm_central_home }}/bin/jboss-cli.sh --file={{ rhdm_central_temp }}/setup.cli"

# SSH keys necessary to git clone (import projects) and push via SSH.

- name: generate SSH key pair {{ rhdm_central_ssh_key }}
  openssh_keypair:
    path: "{{ rhdm_central_ssh_key }}"
  register: openssh_keypair

- name: upload SSH public key to github.com
  local_action:
    module: github_key
    name: rhdm-central
    token: "{{ rhdm_central_github_access_token }}"
    pubkey: "{{ openssh_keypair.public_key }}"
  when: rhdm_central_github_access_token is defined

# Git hook required steps below, knows_hosts needed for the 'git push'.

- name: add {{ rhdm_central_git_hooks_known_hosts }} host key to known_hosts
  known_hosts:
    name: "{{ rhdm_central_git_hooks_known_hosts }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa {{ rhdm_central_git_hooks_known_hosts }}') }}"
  when: rhdm_central_git_hooks_known_hosts is defined

- name: create git-hook directory {{ org_uberfire_nio_git_hooks }}
  file:
    path: "{{ org_uberfire_nio_git_hooks }}"
    state: directory

- name: create git-hook post-commit {{ org_uberfire_nio_git_hooks }}/post-commit
  template:
    src: post-commit.j2
    dest: "{{ org_uberfire_nio_git_hooks }}/post-commit"
    mode: +x

- name: create git-hook messages {{ appformer_git_hooks_bundle }}
  template:
    src: git-hook-messages.properties.j2
    dest: "{{ appformer_git_hooks_bundle }}"
